### ISSUE TITLE
电脑端侧边栏目「主页」指向有问题

### ISSUE THREAD

**Issue by HyperCherry** [b1acksoil/bsblog-v3#1]
~~闲得没事逛GitHub发现的~~
在电脑端上（Chrome、ArchLinux）中，侧边栏的「主页」所指向的链接有问题
「主页」按钮指向的始终是当前所浏览界面，而不是博客主页
![2023-01-23_21-09](https://user-images.githubusercontent.com/20416586/214048255-d16b638e-2b88-44e5-ba56-4d31eaae0db7.png)
（截图中鼠标指针放在了「主页」按钮上，截图截不到鼠标指针）

**Comment by bsdayo** [comment]
感谢反馈！很抱歉一直没有看到xx
是配置文件有问题，已经改正啦
